export const ActionType ={
    SET_PRODUCT :"SET_PRODUCT",
    SELECTED_PRODUCTS:"SELECTED_PRODUCTS",
    ADD_TO_CART:"ADD_TO_CART",
    REMOVE_FROM_CART:"REMOVE_FROM_CART",
    SELECTED_PRODUCT:"SELECTED_PRODUCT",
    TOTAL_PRODUCT:"TOTAL_PRODUCT",
    REMOVE_ALL:"REMOVE_ALL"
}